### ISSUE TITLE
Error when uploading files with no extension

### ISSUE THREAD

**Issue by justync7** [Francesco149/sharenix#23]
> sharenix -m="f" Noextension

        panic: runtime error: slice bounds out of range

        goroutine 1 [running]:
        github.com/Francesco149/sharenix/sharenixlib.ArchiveFile(0xc4200288d8, 0x8, 0x0, 0x0)
                /home/justyn/go/src/github.com/Francesco149/sharenix/sharenixlib/sharenix.go:344 +0x33f
        github.com/Francesco149/sharenix/sharenixlib.ShareNix(0xc42007e2a0, 0x7fffb30dd2d3, 0x1, 0x933116, 0x7, 0xc401000001, 0xc42005adf0, 0x1007fd1cb270a30, 0x0, 0x8, ...)
                /home/justyn/go/src/github.com/Francesco149/sharenix/sharenixlib/sharenix.go:548 +0x138a
        main.handleCLI(0x0, 0xc42001e280)
                /home/justyn/go/src/github.com/Francesco149/sharenix/main.go:138 +0x6e9
        main.main()
                /home/justyn/go/src/github.com/Francesco149/sharenix/main.go:148 +0x22

**Comment by Francesco149** [comment]
right, I haven't thought of that, thanks for the report, will fix
