### ISSUE TITLE
Error while attempting to bind on address ('0.0.0.0', 80)

### ISSUE THREAD

**Issue by ewen-lbh** [Francesco149/sharenix#45]
I ran `airshare -u ewen` which got me a `PermissionError` with the following stacktrace

```sh-session
$ airshare -u ewen                                                                    
Traceback (most recent call last):
  File "/home/ewen/.local/bin/airshare", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ewen/.local/lib/python3.8/site-packages/airshare/cli.py", line 79, in main
    receive_server(code=code, port=port)
  File "/home/ewen/.local/lib/python3.8/site-packages/airshare/receiver.py", line 161, in receive_server
    loop.run_until_complete(site.start())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ewen/.local/lib/python3.8/site-packages/aiohttp/web_runner.py", line 100, in start
    self._server = await loop.create_server(  # type: ignore
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
PermissionError: [Errno 13] error while attempting to bind on address ('0.0.0.0', 80): permission denied
``` 

Some relevant information:

- Python 3.8.2
- Manjaro Linux on kernel 5.6.8-1-MANJARO
- fish shell v. 3.1.1
- pip 20.0.2 from /usr/lib/python3.8/site-packages/pip
- connected to the interneth through a WPA-2 wifi network

**Comment by ewen-lbh** [comment]
I hate myself, wrong repo. You may delete this
